[package]
name = "tinymd"
version = "0.1.0"
edition = "2018"
authors = ["Issa Sugiura"]
description = "A tiny markdown compiler."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
